dblp:
  url: https://dblp.org/search/publ/api?q={}&format=json&h=1000
  topics:
    - "decentralized%20learning%20venue%3AIJCAI%3A"
    - "decentralized%20learning%20venue%3AAAAI%3A"
    - "decentralized%20learning%20venue%3AAISTATS%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Falt%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Fai%3A"
    - "decentralized%20learning%20venue%3ANeurIPS%3A"
    - "decentralized%20learning%20venue%3AICML%3A"
    - "decentralized%20learning%20venue%3AICLR%3A"
    - "decentralized%20learning%20venue%3ACOLT%3A"
    - "decentralized%20learning%20venue%3AUAI%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Fml%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Faccess%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Fjmlr%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Fpami%3A"
    - "decentralized%20learning%20venue%3AKDD%3A"
    - "decentralized%20learning%20venue%3AWSDM%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Fsp%3A"
    - "decentralized%20learning%20venue%3ACCS%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Fuss%3A"
    - "decentralized%20learning%20venue%3ANDSS%3A"
    - "decentralized%20learning%20venue%3ACVPR%3A"
    - "decentralized%20learning%20venue%3AICCV%3A"
    - "decentralized%20learning%20venue%3AECCV%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Fmm%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Fijcv%3A"
    - "decentralized%20learning%20venue%3AACL%3A"
    - "decentralized%20learning%20venue%3ANAACL-HLT%3A"
    - "decentralized%20learning%20venue%3AEMNLP%3A"
    - "decentralized%20learning%20venue%3ACOLING%3A"
    - "decentralized%20learning%20venue%3ASIGIR%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Fsigmod%3A"
    - "decentralized%20learning%20venue%3AICDE%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Fpvldb%3A"
    - "decentralized%20learning%20venue%3ASIGCOMM%3A"
    - "decentralized%20learning%20venue%3AINFOCOM%3A"
    - "decentralized%20learning%20venue%3AMobiCom%3A"
    - "decentralized%20learning%20venue%3ANSDI%3A"
    - "decentralized%20learning%20venue%3AWWW%3A"
    - "decentralized%20learning%20venue%3AOSDI%3A"
    - "decentralized%20learning%20venue%3ASOSP%3A"
    - "decentralized%20learning%20venue%3AISCA%3A"
    - "decentralized%20learning%20venue%3AMLSys%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Feurosys%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Ftpds%3A"
    - "decentralized%20learning%20venue%3ADAC%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Ftocs%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Ftos%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Ftcad%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Ftc%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Ficse%3A"
    - "decentralized%20learning%20streamid%3Ajournals%2Ffocs%3A"
    - "decentralized%20learning%20streamid%3Aconf%2Fstoc%3A"
